language: csharp
solution: MyCalculator.sln
install:
  - nuget restore MyCalculator.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner
  - nuget install OpenCover -Version 4.6.519 -outputdirectory opencover
script:
  - xbuild /p:Configuration=Release MyCalculator.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./MyCalculatorUnitTest/bin/Release/MyCalculatorUnitTest.dll
  - mono ./opencover/OpenCover.4.6.519/tools/OpenCover.Console.exe -target:"./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe" -hideskipped:File -oldStyle -output:./coverage.xml -filter:"+[MyCalculator]*" -register:user